version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - pre-install-steps: 
        - "poetry lock --no-update"
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            pytest
          name: run test

workflows:
  main:
    jobs:
      - build
