# Generated by Django 3.2.12 on 2023-01-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_favobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='favorite_object',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, to='pokemon.favobject'),
        ),
    ]
