# Generated by Django 3.2.12 on 2023-01-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketeam', '0001_initial'),
        ('pokemon', '0004_pokemon_favorite_object'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favobject',
            options={'verbose_name': 'Favorite Object', 'verbose_name_plural': 'Favorite Objects'},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='poketeam.poketeam'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='favorite_object',
            field=models.ForeignKey(default=212, on_delete=django.db.models.deletion.CASCADE, to='pokemon.favobject'),
        ),
    ]
