# Generated by Django 3.2.12 on 2023-01-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poketeam', '0001_initial'),
        ('pokemon', '0005_auto_20230116_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pokemon', to='poketeam.poketeam'),
        ),
    ]
